# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160804_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='', max_length=255, verbose_name='Sub-titulo'),
        ),
    ]
