# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160804_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bodytext',
            field=models.TextField(blank=True, default='', verbose_name='Mensagem'),
        ),
    ]
